### ISSUE TITLE
bug in _guess_and_run_boot

### ISSUE THREAD

**Issue by esheldon** [esheldon/ngmixer#48]
https://github.com/beckermr/ngmixer/blob/master/ngmixer/bootfit.py#L139

Is it not a bug to look at `flags = nbrs_fit_data[n('max_flags')][ind]` without checking first if `nbrs_fit_data` is not None?  And why is this not failing when mof is turned off?

**Comment by beckermr** [comment]
This bug was introduced when you refactored the code in this commit e510fa49e2d3cae05ba39b4e75bd79f06fda18ec. Python logical statements short circuit. The old code  (here https://github.com/beckermr/ngmixer/blob/83b2f5f07062e3edd57527d760fb2be5444720ef/ngmixer/bootfit.py#L147) read

```
if nbrs_fit_data is not None and \ 
nbrs_fit_data[n('max_flags')][new_mb_obs_list.meta['cen_ind']] == 0:
```

This statement is not buggy. If the first expression in the `and` evals to False, then the interpreter moves on.

**Comment by esheldon** [comment]
OK, I'll fix it

**Comment by beckermr** [comment]
Fixed.

**Comment by esheldon** [comment]
On 11/17/15, Matthew R. Becker notifications@github.com wrote:

> Fixed.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/beckermr/ngmixer/issues/48#issuecomment-157455795

err... I was fixing this, I guess we will conflict

## 

Erin Scott Sheldon
Brookhaven National Laboratory erin dot sheldon at gmail dot com

**Comment by beckermr** [comment]
Sorry. I saw another bug that needed fixing too.
